### ISSUE TITLE
Footer Glitch

### ISSUE THREAD

**Issue by kerrtravers** [Sigton/sigton.github.io#10]
Really nice site you've got there, But I found a problem...
![capture](https://user-images.githubusercontent.com/26391179/31509515-b48966d0-af79-11e7-8960-57bea5629aaf.JPG)

I don't think it's meant to do that 😆 

Windows 8.1
Chrome

**Comment by Sigton** [comment]
Huh that's weird? To be honest I'll probably not bother fixing it since I never use it, the sites rather redundant for me...

**Comment by kerrtravers** [comment]
@Sigton Okay 👍
