### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Sheshank-s** [Sigton/sigton.github.io#4]
Maybe calibri? 

Or atleast a different font for the heading.

**Comment by SilversApprentice** [comment]
By the heading do you mean the banner up top or the navigation bar?(or the `<hX>` tags?)

**Comment by SilversApprentice** [comment]
Does my update to style.css please you?

**Comment by Sheshank-s** [comment]
The <hX> Tags :)

**Comment by Sheshank-s** [comment]
I made a pull request.

**Comment by Sigton** [comment]
What's up with the heading font?
I think it looks quite nice...

Sigton

**Comment by SilversApprentice** [comment]
The other font is disturbing, though

**Comment by Sigton** [comment]
Whatcha mean 'disturbing'?
I'm thinking of changing it to the font I use in my banners...

Sigton

**Comment by Sigton** [comment]
I've changed the font to the one in my banner, does that look fine?

Sigton

**Comment by Sigton** [comment]
Someone mentioned somewhere that the font wasn't working; I realised why and is now fixed :)
Also I'm going to close this issue, it has pretty much been resolved.

Sigton
